### ISSUE TITLE
can i uninstall naiveui

### ISSUE THREAD

**Issue by Meguais** [becem-gharbi/nuxt-starter#11]
how can i uninstall naiveui this project ?

**Comment by becem-gharbi** [comment]
In this case, I recommend not to use this starter as it's built around Naive UI. You can start from scratch, add the modules you need and follow the code structure.

**Comment by Meguais** [comment]
I think sidebase/nuxt-auth is being used, can I do the update myself when nuxt-auth update ? what's the difference between your sidebase/nuxt-auth and @bg-dev/nuxt-auth ? and thank you

**Comment by becem-gharbi** [comment]
`sidebase/nuxt-auth` and `bg-dev/nuxt-auth` are two different modules that have nothing in common

**Comment by Meguais** [comment]
oh okey thankyou
