### ISSUE TITLE
Have you considering using Nuxt Layers? 

### ISSUE THREAD

**Issue by kuizuo** [becem-gharbi/nuxt-starter#13]
As the title says, I think as a Starter to start a project quickly with a simple configuration, and [Nuxt Layers](https://nuxt.com/docs/getting-started/layers#layers) was born for it.

Just do the following

```typescript
export default defineNuxtConfig({
  extends: [
    '@bg-dev/awesome',
  ]
})
```

This way, I don't use clone whole repository and make changes based on it。

**Comment by becem-gharbi** [comment]
Hi, thanks for this suggestion,

To be honest I don't believe that this would be beneficial. The intended goal behind this starter is not to build "one size fits all" solution, but rather to think of it as a "starting point" to move fast and customize along the way. Thus I do see that packaging it to a dependency is out of the scope of this project.

**Comment by kuizuo** [comment]
respect, thank for your answer.
