### ISSUE TITLE
I have existing backend. ssr false and output export  

### ISSUE THREAD

**Issue by Meguais** [becem-gharbi/nuxt-starter#21]
Hello, you had prepared a nuxt-auth for me before, but I lost the file. I already have a backend. I want to auth using nuxt-auth. 
To integrate it into tauri, but I need to set my nuxt.config file settings as ssr false and output: "export",

**Comment by becem-gharbi** [comment]
Hi Meguais, the nuxt-auth module used by this project is `@bg-dev/nuxt-auth` so I believe you're refering to it. 

The module's functionality is independent of the rendering mode, in your case no SSR. The backend is built-in the module. However you can create a fork, keep the frontend as is, replace the internal endpoints with the external ones you already have. 

I'm not familiar with Tauri and I'm not sure what do you mean by <output: "export">. If you have a question or a bug to report regading the module feel free to create an issue [there](https://github.com/becem-gharbi/nuxt-auth/issues/new).
